### ISSUE TITLE
Toggling ActiveMods results in render error

### ISSUE THREAD

**Issue by TangyKiwi** [TangyKiwi/KiwiClient#5]
ActiveMods on by default, however when toggled off and on will no longer render.

Error:
com.google.common.eventbus.EventBus$LoggingHandler handleException
SEVERE: Exception thrown by subscriber method onDrawOverlay(com.tangykiwi.kiwiclient.event.DrawOverlayEvent) on subscriber com.tangykiwi.kiwiclient.modules.client.ActiveMods@c8567c9 when dispatching event: com.tangykiwi.kiwiclient.event.DrawOverlayEvent@66b5e5f0
java.util.NoSuchElementException
	at java.base/java.util.ArrayDeque.getLast(ArrayDeque.java:413)
	at net.minecraft.client.util.math.MatrixStack.peek(MatrixStack.java:65)
	at net.minecraft.client.gui.DrawableHelper.fill(DrawableHelper.java:45)
	at com.tangykiwi.kiwiclient.modules.client.ActiveMods.onDrawOverlay(ActiveMods.java:43)
	at jdk.internal.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraft.client.gui.hud.InGameHud.handler$zhi000$render(InGameHud.java:2015)
	at net.minecraft.client.gui.hud.InGameHud.render(InGameHud.java:406)
	at net.minecraft.client.render.GameRenderer.render(GameRenderer.java:855)
	at net.minecraft.client.MinecraftClient.render(MinecraftClient.java:1112)
	at net.minecraft.client.MinecraftClient.run(MinecraftClient.java:728)
	at net.minecraft.client.main.Main.main(Main.java:217)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)
	at net.fabricmc.devlaunchinjector.Main.main(Main.java:86)

**Comment by TangyKiwi** [comment]
Fixed
